name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    jobs:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Install dependencies
        run: go get .

      - name: Clean build directory
        run: make clean

      - name: Build
        run: make out/example

      - name: Test with Go
        run: make test




